#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating PHPCS:\n"

# Check for phpcs
which ./src/vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install PHPCS\033[0m"
  exit 1
fi

RULESET=./src/phpcs.xml

for FILE in $STAGED_FILES
do
  ./src/vendor/bin/phpcs -n --standard="$RULESET" "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
  else
    echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nPHPCS validation completed!\n"

echo "\nValidating Javascript:\n"

# Check for eslint
which ./src/node_modules/.bin/eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m"
  exit 1
fi

STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".(js|vue)\{0,1\}$" | grep -v "node_modules")
if [ ${#STAGED_JS_FILES} -lt 1 ]; then
    echo -e "You have no staged .js or .vue files to test\n"
    exit
fi
for FILE in $STAGED_JS_FILES
do
  ./src/node_modules/.bin/eslint --ext .js,.vue "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nJavascript validation completed!\n"

PASS=false

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS and Eslint but do not. Please fix the PHPCS and Eslint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?