version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/php-fpm
    container_name: fabuks_app
    restart: unless-stopped
    environment:
      SERVICE_NAME: fabuks_app
      SERVICE_TAGS: fabuks_dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fabuks-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: fabuks_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fabuks-network

  #mariadb Service
  mariadb:
    image: mariadb:10.4
    container_name: fabuks_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fabuks
      MYSQL_USER: fabuks
      MYSQL_PASSWORD: 123456
    networks:
      - fabuks-network
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf

  # phpmyadmin Service
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8088:80'
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - fabuks-network

#Docker Networks
networks:
  fabuks-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
